import? "./tmp.just"

_default:
  @just -f ~/.config/global_justfile/justfile --choose

[no-cd]
commit_ai:
  git commit -m "$(git diff --staged | ask -n 'write me a one sentence commit message for these changes')"

s:
  just -f ~/.config/dotfiles/justfile switch
