[gdrive]
type = drive
scope = drive
token = {"access_token":"ya29.a0AfH6SMD87PvXc0sqMdrlx-xe7FHMst6U_-Kzpxz2BMc3Vu24xdeQimbQkgbIxYKiDCA5kKW2SGzigQWHHja7it0bOCJaYggvuUHgVoUjoSZ2WJGXONEcK8kHBNBe7dy2OUOl7i5YK5-_jYoKUXNhS_MUlQbVrukYJFWPBfNt2DM","token_type":"Bearer","refresh_token":"1//076Q7ktglGFaCCgYIARAAGAcSNwF-L9Ir9CaGaQwdi0FbcYF_9EIC5Nwuy270APcgQq4mcsQq1gwCE1mnJJtkxnNleKT12j20NdU","expiry":"2021-01-06T16:14:38.670441064Z"}

[tdrive]
type = drive
scope = drive
token = {"access_token":"ya29.a0AfH6SMAWqB833cgNlJelNOZE8m1Q0IYJSADhMkAuoKs9yyHcVb6lM9Af-8xIO3BDEisds5b85f69WJV8qFw-aFzVBFuOwOFY2CYw4MKpffXqS5jZKkU6IhPUN26vZ-VwH5DxY3SfBRUCLoVzwgbxN3zxyn-KV5pJOE9jBTOdEyw","token_type":"Bearer","refresh_token":"1//07erp52jU6_WiCgYIARAAGAcSNwF-L9IrSBYiQ3xGL1msj79dsmriTi24153tKHLnVhS6_-b3LuERr7DCsk8qum76JbYQZjj1Fbo","expiry":"2021-01-18T13:16:34.072645075Z"}
