# File: .github/workflows/trufflehog-scan.yml

# 1. Name of the workflow
name: 'TruffleHog Secrets Scan'

# 2. When the workflow will run
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# 3. The jobs to run
jobs:
  trufflehog:
    name: TruffleHog Scan
    runs-on: ubuntu-latest

    steps:
      # 4. Check out the repository's code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Fetch all history for a deeper scan
          fetch-depth: 0

      # 5. Run the TruffleHog scan
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@v3.90.8
        with:
          # Tell TruffleHog where to scan
          path: .
          # Use extra arguments to fail the build if secrets are found
          extra_args: --only-verified
